### ISSUE TITLE
How can we use vue-dynamic with vuetify or eleme-fe ? Could you add sample?

### ISSUE THREAD

**Issue by glikoz** [JounQin/vue-dynamic#14]
I've added script and css for vuetify to your demo (https://jounqin.github.io/vue-dynamic/)

to header:
`<link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons'
        rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.min.css"
        rel="stylesheet"><meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui" name="viewport">`

to body:

<script src="https://cdn.jsdelivr.net/npm/vuetify/dist/vuetify.js"></script>  (after vue-dynamic)

But I'm getting Unable to locate target error.

![image](https://user-images.githubusercontent.com/1757659/43062219-c47ad256-8e60-11e8-9964-958ca8079f4f.png)

Could you add very simple example.

**Comment by JounQin** [comment]
Would you mind to provide a runnable reproduction link like http://jsfiddle.net?

**Comment by glikoz** [comment]
https://jsfiddle.net/glikoz/ox5jcb08/1/
Thanks.

**Comment by JounQin** [comment]
https://vuetifyjs.com/en/getting-started/frequently-asked-questions
You can read about section *My application does not look correct* about wrapper `v-app` or attribute `data-app="true"`.

fixed demo: https://jsfiddle.net/ox5jcb08/7/

**Comment by glikoz** [comment]
Thanks @JounQin .
