### ISSUE TITLE
Replacement html element to vue-dynamic bind data

### ISSUE THREAD

**Issue by tugrulugurlu** [JounQin/vue-dynamic#20]
Hi @JounQin ,

i want to do replace html tag to vue-dynamic tag after bind data vue-dynamic companent. How can I to do

`
template = "<div>" + settings.comps[0].data.template.replace("", "<dynamic  :comps="comps1" />) + "</div>";
`
After replacement How I do comps1 bind to inserted dynamic companent

I get error: Unknown custom element: <Dynamic> - did you register the component correctly? For recursive components, make sure to provide the

**Comment by JounQin** [comment]
Please provide a minimize runnable reproduction.

**Comment by tugrulugurlu** [comment]
Hi @JounQin 

sorry I cant provide minimize application. Because I am developing aspnet core application and my company not release application yet. But I try to explain with examples

`
axios.get('/api/dynamic/prod1001')
.then(function (response) {
	//response.data.template =  'dynamic :comps="comps1" :emptyView="NoItem"'

	companents.comps1 = {
		template: '<dynamic :comps="comps1" :emptyView="NoItem" />', //response.data.template
		data(){
			return storage
		}
	};
});
`

[Vue warn]: Unknown custom element: Dynamic - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by tugrulugurlu** [comment]
Hi @JounQin 

When I register vue-dynamic at global my problem is solved

Thanks.

**Comment by JounQin** [comment]
OK, then I'm going to close it.

When you're not registering it globally, the `dynamic` component couldn't be accessed directly.
