### ISSUE TITLE
Emitted events  don't propagate

### ISSUE THREAD

**Issue by LouWii** [JounQin/vue-dynamic#23]
Hi,

Thanks for making vue-dynamic.

I'm using it to display a form, here's how I create `comps`

```
[{
    data: {formModel: {field1: 'text', field2: 'text'}},
    methods: {onSubmit: "this.$emit('formSubmitted', this.formModel);"},
    template: '<form>....</form>'
}]
```

Everything is working fine, the form displays, field models react properly and I can see that the event is triggered in the Vue debugger extension.

However, when I listen to the event on `<dynamic>`, it doesn't seem to be triggered. 

```
<dynamic :comps="comps" :emptyView="emptyView" v-on:form-submitted="handleForm"/>
```

`handleForm` is never called.

Looking at the components tree in Vue debugger, I see that the event comes from `<Dynamic_0>`, and that element has a `<Dynamic_Root>`. It seems that the event is stopped at `<Dynamic_Root>` and not propagated to the parent.

Is there a way to go around that?

Thanks

**Comment by JounQin** [comment]
Thanks for reporting, I'll check if we can achieve it.

**Comment by JounQin** [comment]
@LouWii It is supported at 0.3.0 now.

**Comment by LouWii** [comment]
That was crazy fast! Thanks!
