### ISSUE TITLE
npm build Module parse failed error problem

### ISSUE THREAD

**Issue by tugrulugurlu** [JounQin/vue-dynamic#25]
Hi @JounQin 

how can I solve this problem

    ERROR in ./~/vue-dynamic/lib/dynamic.js
    Module parse failed: \node_modules\vue-dynamic\lib\dynamic.js Unexpected token (56:58)
    You may need an appropriate loader to handle this file type.
    |
    |     if (data) {
    |       component.data = isFunction(data) ? data : () => ({ ...data })
    |     }
    |
     @ ./~/vue-dynamic/lib/index.js 1:0-31
     @ ./ClientApp/app.js
     @ ./ClientApp/boot-app.js

**Comment by JounQin** [comment]
@tugrulugurlu You can add an `alias: {'vue-dynamic$': 'vue-dynamic/dist/vue-dynamic.js'}` temporarily, I will check to improve it as possible as soon.

**Comment by JounQin** [comment]
@tugrulugurlu Please check v0.3.1

**Comment by tugrulugurlu** [comment]
Hi @JounQin 

Thank you for v0.3.1. My problem solved.
