### ISSUE TITLE
Vuetify used within template causes "Unknown custom element"

### ISSUE THREAD

**Issue by reidja** [JounQin/vue-dynamic#50]
Vuetify used within template causes "Unknown custom element"

Vuetify is registered globally with:

```js
Vue.use(Vuetify);
```

Vuetify is working fine in VueJS but the following code triggers "Unknown custom element <v-btn>"

I can use `<v-btn>` normally in other templates?

This does not work:

```vue
<template>
  <Dynamic :comps="comps" :emptyView="emptyView" />
</template>

<script>
import Error  from './Error.vue';


export default {
  data() {
    return {
      emptyView: Error,
      comps: [{
        template: `<div><v-btn>HI</v-btn></div>`,
      }]
    }
  },
};
</script>
```

This does work:

```vue
<template>
  <v-btn>Hi</v-btn>
</template>

<script>

export default {};
</script>
```

**Comment by reidja** [comment]
Sorry, accidentally closed!

**Comment by JounQin** [comment]
I'll take a look ASAP.

**Comment by JounQin** [comment]
@reidja I tried locally and it does work. This component requires full build of vue, you can try to alias `vue` to `vue/dist/vue.esm.js`.

https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds

If it does not work, please provide a minimal runnable reproduction.

**Comment by reidja** [comment]
For anyone who encounters this in the future, it's not so much an issue with vue-dynamic as it is with how vuetify works.

It doesn't appear as though vuetify loads its components normally (something about: a la carte / treeshaking / vuetify-loader).

If you are using Vue CLI you won't be able to use these components in the runtime compiler, let alone within vue-dynamic.

As an example, this *WILL* work

```vue
<template>
  <v-btn>HI</v-btn>
</template>

<script>
export default {};
</script>
```

However this will *NOT*:

```vue
<script>
export default {
    template: `<v-btn>HI</v-btn>`
}
</script>
```

The second one will complain about the component not being registered.

The only solution I could come up with was to manually register the components I would be using.

```vue
<script>
import Vue from 'vue';
import {  VBtn } from 'vuetify/lib';

Vue.component('v-btn', VBtn);

export default {
    template: `<v-btn>HI</v-btn>`
}
</script>
```

The above does appear to work but I'm not sure how good of an idea it is.
